version: 2
jobs:
  build:
    docker: #执行容器
      - image: circleci/node:v12.5.0 #依赖环境
    steps:
      - run: 
          name: Install
          command: npm install
      - run: 
          name: Test
          command: npm run test
      - run:
          name: Build
          command: npm run build
      - run: 
          name: coveralls
          command: npm run coveralls