version: 2
jobs:
  build:
    steps:
      - run: 
          name: Install
          command: npm install
      - run:
          name: Build
          command: npm run build
      - run: 
          name: coveralls
          command: npm run coveralls